//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : Database
	/// Data Source    : Database
	/// Server Version : 3.24.0
	/// </summary>
	public partial class DatabaseDB : LinqToDB.Data.DataConnection
	{
		public ITable<Category> Categories { get { return this.GetTable<Category>(); } }

		public DatabaseDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DatabaseDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("category")]
	public partial class Category
	{
		[Column("id"),       PrimaryKey,  NotNull] public long   Id       { get; set; } // integer
		[Column("name"),        Nullable         ] public string Name     { get; set; } // text(max)
		[Column("parentId"),    Nullable         ] public long?  ParentId { get; set; } // integer
		[Column("isdata"),      Nullable         ] public long?  Isdata   { get; set; } // integer
	}

	public static partial class TableExtensions
	{
		public static Category Find(this ITable<Category> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}

#pragma warning restore 1591
